services:
  chatbot-backend:
    build: 
      context: .
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app 
      - ./app/database:/app/database 

  chatbot-frontend:
    build:
      context: ./chat
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./chat:/chat
    depends_on:
      - chatbot-backend
